import useClient from 'next/dist/next-server/server/api-utils';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Government_News_App",
  description: "Generated by create next app",
};

export default function  RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
      <main className={inter.className}>
          {children}
      </main>
      <Footer /> 
      </body>
    </html>
  );
}
